language: python
sudo: false

matrix:
    include:
        - python: 3.3

        - python: 3.4

        - python: 3.5

        - python: 3.6

install:
  - python3.6 setup.py install

script: python3.6 bioplib.py
